#ifndef ART_H
#define ART_H

const int FONT_SHEET_X_CELLS = 16;
const int FONT_SHEET_Y_CELLS = 7;
const int TILE_SHEET_X_CELLS = 19;
const int TILE_SHEET_Y_CELLS = 11;

enum class TileId
{
    empty,
    playerFirearm,
    playerMelee,
    zombieUnarmed,
    zombieArmed,
    zombieBloated,
    cultistFirearm,
    cultistDagger,
    witchOrWarlock,
    ghoul,
    mummy,
    deepOne,
    shadow,
    lengElder,
    theDarkOne,
    ape,
    armor,
    potion,
    ammo,
    scroll,
    elderSign,
    chestClosed,
    chestOpen,
    amulet,
    ring,
    electricLantern,
    medicalBag,
    mask,
    rat,
    spider,
    wolf,
    phantasm,
    ratThing,
    hound,
    bat,
    byakhee,
    massOfWorms,
    ooze,
    gasSpore,
    polyp,
    fungi,
    vortex,
    ghost,
    wraith,
    mantis,
    locust,
    migoArmor,
    pistol,
    tommyGun,
    shotgun,
    dynamite,
    dynamiteLit,
    molotov,
    incinerator,
    migoGun,
    flare,
    flareGun,
    flareLit,
    dagger,
    crowbar,
    axe,
    club,
    hammer,
    machete,
    pitchfork,
    sledgeHammer,
    rock,
    ironSpike,
    pharaohStaff,
    lockpick,
    huntingHorror,
    spiderLeng,
    chthonian,
    migo,
    floor,
    aimMarkerHead,
    aimMarkerTrail,
    wallTop,
    wallFrontAlt1,
    wallFrontAlt2,
    wallFront,
    squareCheckered,
    rubbleHigh,
    rubbleLow,
    stairsDown,
    leverLeft,
    leverRight,
    device1,
    device2,
    cabinetClosed,
    cabinetOpen,
    pillarBroken,
    pillar,
    pillarCarved,
    barrel,
    sarcophagus,
    caveWallFront,
    caveWallTop,
    egyptWallFront,
    egyptWallTop,
    monolith,
    brazier,
    altar,
    web,
    doorClosed,
    doorOpen,
    doorBroken,
    fountain,
    tree,
    bush,
    churchBench,
    graveStone,
    tombOpen,
    tombClosed,
    water1,
    water2,
    trapGeneral,
    cocoonOpen,
    cocoonClosed,
    blast1,
    blast2,
    corpse,
    corpse2,
    projectileStdFrontSlash,
    projectileStdBackSlash,
    projectileStdDash,
    projectileStdVerticalBar,
    gore1,
    gore2,
    gore3,
    gore4,
    gore5,
    gore6,
    gore7,
    gore8,
    smoke,
    trapezohedron,
    pit,
    popupTopL,
    popupTopR,
    popupBtmL,
    popupBtmR,
    popupHor,
    popupVer,
    hangbridgeVer,
    hangbridgeHor,
    scorchedGround,
    popupHorDown,
    popupHorUp,
    popupVerR,
    popupVerL,
    stalagmite
};


struct Pos;

namespace Art
{

Pos getGlyphPos(const char glyph);
Pos getTilePos(const TileId tile);

} //Art

#endif
