#include <string>
#include <vector>
#include <math.h>

#include "ActorData.h"

#include "ConstDungeonSettings.h"
#include "Converters.h"
#include "Item.h"
#include "Engine.h"

using namespace std;

void ActorDefinition::reset() {
  devName = actor_empty;
  name_a = "";
  name_the = "";
  tile = tile_empty;
  glyph = 'X';
  color = clrYellow;
  monsterLvl = 1;
  groupSize = monsterGroupSize_alone;
  hpMax = 1;
  speed = actorSpeed_normal;
  moveType = moveType_walk;
  rangedCooldownTurns = spellCooldownTurns = 0;
  isResPhys = isResFire = isResCold = isResAcid = isResElectric = isResSpirit = false;
  isImmunePhys = isImmuneFire = isImmuneCold = isImmuneAcid = isImmuneElectric = isImmuneSpirit = false;
  isResLight = isImmuneLight = true;
  abilityValues.reset();
  aiBehavior.reset();
  nrTurnsAwarePlayer = 0;
  spawnMinLevel = spawnMaxLevel = 999;
  actorSize = actorSize_humanoid;
  isHumanoid = false;
  isAutoDescriptionAllowed = true;
  deathMessageOverride = "";
  nrOfKills = 0;
  canOpenDoors = canBashDoors = false;
  nrLeftAllowedToSpawn = -1;
  isUnique = false;
  isAutoSpawnAllowed = true;
  spellCastMessage = "[SPELL MESSAGE HERE]";
  erraticMovement = actorErratic_rare;
  shockValue = shockValue_none;
  isRat = isCanine = isSpider = isUndead = false;
  canBeSummoned = false;
  canBleed = true;
  canDodge = true;
  nativeRooms.resize(0);
  description = "";
  aggroTextMonsterSeen = "";
  aggroTextMonsterHidden = "";
}

void ActorData::setStrengthsFromFormula(ActorDefinition& d, const EntityStrength_t hpStrength) const {
  //Set HP from progression formula
  const int HP_BASE = 2;
  const int HP_INCR = 2;
  const int HP_CAP = 999;

  const int EFFECTIVE_LEVEL_BON_FROM_UNIQUE = d.isUnique ? 4 : 0;
  const int EFFECTIVE_LEVEL = d.monsterLvl + EFFECTIVE_LEVEL_BON_FROM_UNIQUE;

  const int HP_BEFORE_STRENGTH = HP_BASE + HP_INCR * (EFFECTIVE_LEVEL - 1);
  const double STRENGTH_FACTOR = EntityStrength::getFactor(hpStrength);
  const int HP_AFTER_STRENGTH = static_cast<int>(ceil(static_cast<double>(HP_BEFORE_STRENGTH) * STRENGTH_FACTOR));
  const int HP_AFTER_CAP = min(HP_CAP, HP_AFTER_STRENGTH);
  d.hpMax = HP_AFTER_CAP;

  //Set weapon abilities from progression formula
  const int ATTACK_BASE = 10;
  const double ATTACK_INCR = 5.0;
  const int ATTACK_CAP = 40;

  const int ATTACK = static_cast<int>(ceil(static_cast<double>(ATTACK_BASE) + ATTACK_INCR * static_cast<double>(EFFECTIVE_LEVEL - 1)));
  const int ATTACK_AFTER_CAP = min(ATTACK_CAP, ATTACK);

  d.abilityValues.setAbilityValue(ability_accuracyMelee, ATTACK_AFTER_CAP);
  d.abilityValues.setAbilityValue(ability_accuracyRanged, ATTACK_AFTER_CAP);
}

void ActorData::defineAllActors() {
  ActorDefinition d;
  d.reset();
  finalizeDefinition(d);

  d.name_a = "Player";
  d.name_the = "Player";
  d.moveType = moveType_walk;
  d.devName = actor_player;
  d.hpMax = 16;
  d.speed = actorSpeed_normal;
  d.glyph = '@';
  d.color = clrWhiteHigh;
  d.tile = tile_playerFirearm;
  d.isAutoSpawnAllowed = false;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Reanimated Corpse";
  d.name_the = "The Reanimated Corpse";
  d.moveType = moveType_walk;
  d.devName = actor_zombie;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.glyph = 'Z';
  d.color = clrBrown;
  d.tile = tile_zombieUnarmed;
  d.spawnMinLevel = 1;
  d.monsterLvl = 2;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 12;
  d.description = "This rotting thing appears to have been brought back to life through some abominable process. It has grown sharp claws to attack with.";
  d.aggroTextMonsterSeen = d.name_the + " growls at me.";
  d.aggroTextMonsterHidden = "I hear a growling voice.";
  d.erraticMovement = actorErratic_somewhat;
  d.shockValue = shockValue_some;
  d.isUndead = true;
  setStrengthsFromFormula(d, normal);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Reanimated Corpse";
  d.name_the = "The Reanimated Corpse";
  d.moveType = moveType_walk;
  d.devName = actor_zombieAxe;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.glyph = 'Z';
  d.color = clrGray;
  d.tile = tile_zombieArmed;
  d.spawnMinLevel = 2;
  d.monsterLvl = 3;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 10;
  d.description = "This rotting thing appears to have been brought back to life through some abominable process. It is wielding a rusty axe.";
  d.aggroTextMonsterSeen = d.name_the + " growls at me.";
  d.aggroTextMonsterHidden = "I hear a growling voice.";
  d.erraticMovement = actorErratic_somewhat;
  d.shockValue = shockValue_some;
  d.isUndead = true;
  setStrengthsFromFormula(d, normal);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Bloated Corpse";
  d.name_the = "The Bloated Corpse";
  d.moveType = moveType_walk;
  d.devName = actor_bloatedZombie;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 20;
  d.glyph = 'Z';
  d.color = clrWhiteHigh;
  d.tile = tile_zombieBloated;
  d.spawnMinLevel = 3;
  d.monsterLvl = 4;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 50;
  d.description = "This lumbering giant corpse seems to be artificially bloated somehow. It is constantly oozing putrid liquid that it can spit to attack with.";
  d.erraticMovement = actorErratic_rare;
  d.shockValue = shockValue_some;
  d.isUndead = true;
  setStrengthsFromFormula(d, strong);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "Major Clapham-Lee";
  d.name_the = "Major Clapham-Lee";
  d.moveType = moveType_walk;
  d.devName = actor_majorClaphamLee;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.glyph = 'Z';
  d.color = clrCyanLight;
  d.tile = tile_zombieUnarmed;
  d.spawnMinLevel = 4;
  d.monsterLvl = 4;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 999;
  d.description
  = "Major Sir Eric Moreland Clapham-Lee was once a commanding officer during the Great War. Shortly after his plane was shot down, his body was stolen. Now he roams these halls as a resurrected warrior in service of the cult, commanding a squad of undead.";
  d.erraticMovement = actorErratic_somewhat;
  d.shockValue = shockValue_heavy;
  d.isUndead = true;
  d.isUnique = true;
  d.nrLeftAllowedToSpawn = 1;
  setStrengthsFromFormula(d, strong);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "Dean Halsey";
  d.name_the = "Dean Halsey";
  d.moveType = moveType_walk;
  d.devName = actor_deanHalsey;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.glyph = 'Z';
  d.color = clrCyan;
  d.tile = tile_zombieUnarmed;
  d.isAutoSpawnAllowed = false;
  d.spawnMinLevel = 4;
  d.monsterLvl = 4;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 999;
  d.description
  = "Alan Halsey was the dean of the Miskatonic University in New England. Somehow he must have gotten into the hands of the Cult, who turned him into the hellish zombie warrior I now see before me.";
  d.erraticMovement = actorErratic_rare;
  d.shockValue = shockValue_heavy;
  d.isUndead = true;
  d.isUnique = true;
  d.nrLeftAllowedToSpawn = 0;
  setStrengthsFromFormula(d, strong);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Cultist";
  d.name_the = "The Cultist";
  d.moveType = moveType_walk;
  d.devName = actor_cultist;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 3;
  d.spellCooldownTurns = 6;
  d.glyph = 'P';
  d.color = clrGray;
  d.tile = tile_cultistFirearm;
  d.spawnMinLevel = 1;
  d.spawnMaxLevel = FIRST_CAVERN_LEVEL - 1;
  d.monsterLvl = 3;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canOpenDoors = true;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 25;
  d.description = "A fanatic cultist of the lowest rank, madly gibbering in some half-lost language.";
  d.spellCastMessage = "The accolyte makes strange gestures in the air.";
  d.erraticMovement = actorErratic_rare;
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Cultist";
  d.name_the = "The Cultist";
  d.moveType = moveType_walk;
  d.devName = actor_cultistTeslaCannon;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 3;
  d.spellCooldownTurns = 6;
  d.glyph = 'P';
  d.color = clrYellow;
  d.tile = tile_cultistFirearm;
  d.spawnMinLevel = 7;
  d.spawnMaxLevel = FIRST_CAVERN_LEVEL - 1;
  d.monsterLvl = 4;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canOpenDoors = true;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 25;
  d.description = "A fanatic cultist of the lowest rank, madly gibbering in some half-lost language. It is wielding a Tesla Cannon.";
  d.spellCastMessage = "The accolyte makes strange gestures in the air.";
  d.erraticMovement = actorErratic_rare;
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Cultist";
  d.name_the = "The Cultist";
  d.moveType = moveType_walk;
  d.devName = actor_cultistSpikeGun;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 3;
  d.spellCooldownTurns = 6;
  d.glyph = 'P';
  d.color = clrBlueLight;
  d.tile = tile_cultistFirearm;
  d.spawnMinLevel = 4;
  d.spawnMaxLevel = FIRST_CAVERN_LEVEL - 1;
  d.monsterLvl = 5;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canOpenDoors = true;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 25;
  d.description = "A fanatic cultist of the lowest rank, madly gibbering in some half-lost language. It is wielding a Spike gun.";
  d.spellCastMessage = "The accolyte makes strange gestures in the air.";
  d.erraticMovement = actorErratic_rare;
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "Keziah Mason";
  d.name_the = "Keziah Mason";
  d.moveType = moveType_walk;
  d.devName = actor_keziahMason;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 3;
  d.glyph = 'P';
  d.color = clrMagenta;
  d.tile = tile_witchOrWarlock;
  d.nrLeftAllowedToSpawn = 1;
  d.isUnique = true;
  d.spawnMinLevel = 3;
  d.monsterLvl = 3;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.description
  = "During the Salem witch trials of 1692 an old woman by the name of Keziah Mason was arrested for her suspicious behavior and seeming insight into other worlds. In her testimony to the judge, she confessed to having signed her name in the Black Book of Azathoth, and of her secret name of Nahab. She later disappeared mysteriously from Salem. She is described as having a \"bent back, long nose, and shrivelled chin\" and has a \"croaking voice\". She has an animal familier; the rat Brown Jenkin, which she trusts to carry messages between her and the devil. She feeds this creature on her blood.";
  d.spellCastMessage = "Keziah makes strange gestures in the air.";
  d.nrTurnsAwarePlayer = 999;
  d.erraticMovement = actorErratic_rare;
  d.shockValue = shockValue_some;
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "The Lord of Pestilence";
  d.name_the = "The Lord of Pestilence";
  d.moveType = moveType_walk;
  d.devName = actor_lordOfPestilence;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 2;
  d.glyph = 'P';
  d.color = clrRedLight;
  d.tile = tile_witchOrWarlock;
  d.nrLeftAllowedToSpawn = 0;
  d.isUnique = true;
  d.spawnMinLevel = 100;
  d.monsterLvl = 15;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.description = "Asdf";
  d.spellCastMessage = "The Lord of Pestilence makes strange gestures in the air.";
  d.nrTurnsAwarePlayer = 999;
  d.erraticMovement = actorErratic_rare;
  d.shockValue = shockValue_some;
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "The Lord of Shadows";
  d.name_the = "The Lord of Shadows";
  d.moveType = moveType_walk;
  d.devName = actor_lordOfShadows;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 2;
  d.glyph = 'P';
  d.color = clrRedLight;
  d.tile = tile_witchOrWarlock;
  d.nrLeftAllowedToSpawn = 0;
  d.isUnique = true;
  d.spawnMinLevel = 100;
  d.monsterLvl = 15;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.description
  = "Asdf";
  d.spellCastMessage = "The Lord of Shadows makes strange gestures in the air.";
  d.nrTurnsAwarePlayer = 999;
  d.erraticMovement = actorErratic_rare;
  d.shockValue = shockValue_some;
  setStrengthsFromFormula(d, weak);
  d.abilityValues.setAbilityValue(ability_stealth, 90);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "The Lord of Spiders";
  d.name_the = "The Lord of Spiders";
  d.moveType = moveType_walk;
  d.devName = actor_lordOfSpiders;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 2;
  d.glyph = 'P';
  d.color = clrRedLight;
  d.tile = tile_witchOrWarlock;
  d.nrLeftAllowedToSpawn = 0;
  d.isUnique = true;
  d.spawnMinLevel = 100;
  d.monsterLvl = 15;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.description
  = "Asdf";
  d.spellCastMessage = "The Lord of Spiders makes strange gestures in the air.";
  d.nrTurnsAwarePlayer = 999;
  d.erraticMovement = actorErratic_rare;
  d.shockValue = shockValue_some;
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "The Lord of Spirits";
  d.name_the = "The Lord of Spirits";
  d.moveType = moveType_ethereal;
  d.devName = actor_lordOfSpirits;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 2;
  d.glyph = 'P';
  d.color = clrRedLight;
  d.tile = tile_witchOrWarlock;
  d.nrLeftAllowedToSpawn = 0;
  d.isUnique = true;
  d.spawnMinLevel = 100;
  d.monsterLvl = 15;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.description
  = "Asdf";
  d.spellCastMessage = "The Lord of Spirits makes strange gestures in the air.";
  d.nrTurnsAwarePlayer = 999;
  d.erraticMovement = actorErratic_rare;
  d.shockValue = shockValue_some;
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Cultist Priest";
  d.name_the = "The Cultist Priest";
  d.moveType = moveType_walk;
  d.devName = actor_cultistPriest;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 3;
  d.glyph = 'P';
  d.color = clrCyanLight;
  d.tile = tile_cultistDagger;
  d.spawnMinLevel = 5;
  d.spawnMaxLevel = FIRST_CAVERN_LEVEL - 1;
  d.monsterLvl = 5;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canOpenDoors = true;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 25;
  d.description = "A fanatic cultist of the priest rank, madly gibbering in some half-lost language.";
  d.spellCastMessage = "The priest makes strange gestures in the air.";
  d.erraticMovement = actorErratic_rare;
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Green Spider";
  d.name_the = "The Green Spider";
  d.moveType = moveType_walk;
  d.devName = actor_greenSpider;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 's';
  d.color = clrGreenLight;
  d.tile = tile_spider;
  d.spawnMinLevel = 1;
  d.spawnMaxLevel = 7;
  d.monsterLvl = 1;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 5;
  d.description = "A large green spider.";
  d.erraticMovement = actorErratic_somewhat;
  d.isSpider = true;
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A White Spider";
  d.name_the = "The White Spider";
  d.moveType = moveType_walk;
  d.devName = actor_whiteSpider;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 's';
  d.color = clrWhiteHigh;
  d.tile = tile_spider;
  d.spawnMinLevel = 1;
  d.spawnMaxLevel = 7;
  d.monsterLvl = 1;
  d.groupSize = monsterGroupSize_group;
  d.nrTurnsAwarePlayer = 5;
  d.actorSize = actorSize_floor;
  d.description = "A large white spider.";
  d.erraticMovement = actorErratic_somewhat;
  d.isSpider = true;
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Black Spider";
  d.name_the = "The Black Spider";
  d.moveType = moveType_walk;
  d.devName = actor_blackSpider;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 's';
  d.color = clrGray;
  d.tile = tile_spider;
  d.spawnMinLevel = 1;
  d.spawnMaxLevel = 7;
  d.monsterLvl = 1;
  d.groupSize = monsterGroupSize_group;
  d.nrTurnsAwarePlayer = 5;
  d.actorSize = actorSize_floor;
  d.description = "A large black spider.";
  d.erraticMovement = actorErratic_somewhat;
  d.isSpider = true;
  setStrengthsFromFormula(d, normal);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Leng-Spider";
  d.name_the = "The Leng-Spider";
  d.moveType = moveType_walk;
  d.devName = actor_lengSpider;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_fast;
  d.rangedCooldownTurns = 0;
  d.glyph = 'S';
  d.color = clrMagenta;
  d.tile = tile_spiderLeng;
  d.spawnMinLevel = 10;
  d.monsterLvl = 10;
  d.groupSize = monsterGroupSize_few;
  d.nrTurnsAwarePlayer = 20;
  d.actorSize = actorSize_giant;
  d.description
  = "Leng spiders are huge, purplish arachnids, with pustulent bloated bodies and long, bristly legs. Native to the Dreamlands, the spiders of Leng are intelligent, dangerous, and gigantic.";
  d.erraticMovement = actorErratic_somewhat;
  d.isSpider = true;
  d.shockValue = shockValue_some;
  setStrengthsFromFormula(d, strong);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Fire hound";
  d.name_the = "The Fire hound";
  d.moveType = moveType_walk;
  d.devName = actor_fireHound;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.abilityValues.setAbilityValue(ability_dodgeAttack, 35);
  d.speed = actorSpeed_fast;
  d.rangedCooldownTurns = 10;
  d.glyph = 'd';
  d.color = clrRed;
  d.tile = tile_hound;
  d.spawnMinLevel = 9;
  d.monsterLvl = 7;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_floor;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 25;
  d.description = "This extremely aggressive canine seems to be part corporeal and part fire. It breathes searing flames.";
  d.erraticMovement = actorErratic_somewhat;
  d.shockValue = shockValue_some;
  d.isCanine = true;
  d.canBeSummoned = true;
  setStrengthsFromFormula(d, normal);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Ghost";
  d.name_the = "The Ghost";
  d.moveType = moveType_ethereal;
  d.devName = actor_ghost;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 'G';
  d.color = clrGray;
  d.tile = tile_ghost;
  d.spawnMinLevel = 3;
  d.monsterLvl = 3;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.nrTurnsAwarePlayer = 5;
  d.description = "A restless spirit?";
  d.erraticMovement = actorErratic_somewhat;
  d.shockValue = shockValue_heavy;
  d.isUndead = true;
  d.canBeSummoned = true;
  d.deathMessageOverride = "The Ghost is put to rest.";
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Phantasm";
  d.name_the = "The Phantasm";
  d.moveType = moveType_ethereal;
  d.devName = actor_phantasm;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 'G';
  d.color = clrWhite;
  d.tile = tile_phantasm;
  d.spawnMinLevel = 7;
  d.monsterLvl = 7;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.nrTurnsAwarePlayer = 5;
  d.description
  = "It exists between the land of the dead and the living. It resembles a grim reaper, including the cloak, scythe, and skeletal appearance.";
  d.erraticMovement = actorErratic_very;
  d.shockValue = shockValue_heavy;
  d.isUndead = true;
  d.canBeSummoned = true;
  d.deathMessageOverride = "The Phantasm is put to rest.";
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Wraith";
  d.name_the = "The Wraith";
  d.moveType = moveType_fly;
  d.devName = actor_wraith;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 10;
  d.glyph = 'G';
  d.color = clrRed;
  d.tile = tile_wraith;
  d.spawnMinLevel = 12;
  d.monsterLvl = 12;
  d.groupSize = monsterGroupSize_alone;
  d.spellCastMessage = "The Wraith casts a spell";
  d.actorSize = actorSize_humanoid;
  d.nrTurnsAwarePlayer = 5;
  d.description = "A powerful spirit.";
  d.erraticMovement = actorErratic_somewhat;
  d.shockValue = shockValue_heavy;
  d.isUndead = true;
  d.canBeSummoned = true;
  d.deathMessageOverride = "The Wraith is put to rest.";
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Rat";
  d.name_the = "The Rat";
  d.moveType = moveType_walk;
  d.devName = actor_rat;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = false;
  d.speed = actorSpeed_sluggish;
  d.rangedCooldownTurns = 0;
  d.glyph = 'r';
  d.color = clrGray;
  d.tile = tile_rat;
  d.spawnMinLevel = 1;
  d.spawnMaxLevel = 6;
  d.monsterLvl = 1;
  d.groupSize = monsterGroupSize_horde;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 5;
  d.description = "A large and aggressive rodent.";
  d.erraticMovement = actorErratic_somewhat;
  d.isRat = true;
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Rat-thing";
  d.name_the = "The Rat-thing";
  d.moveType = moveType_walk;
  d.devName = actor_ratThing;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = false;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 'r';
  d.color = clrBrown;
  d.tile = tile_ratThing;
  d.spawnMinLevel = 1;
  d.spawnMaxLevel = 7;
  d.monsterLvl = 1;
  d.groupSize = monsterGroupSize_horde;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 5;
  d.description
  = "At first sight, a Rat-thing can easily be mistaken for a large, dark rat. On closer examination, however, their human hands and evil caricatures of human heads reveal their unnatural nature. Rat-things are said to be created from dead cultists by foul witchcraft. Thus, they are found where the witch who created them had her lair.";
  d.erraticMovement = actorErratic_somewhat;
  d.shockValue = shockValue_mild;
  d.isRat = true;
  setStrengthsFromFormula(d, strong);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "Brown Jenkin";
  d.name_the = "Brown Jenkin";
  d.moveType = moveType_walk;
  d.devName = actor_brownJenkin;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.glyph = 'r';
  d.color = clrBrownDark;
  d.tile = tile_ratThing;
  d.isAutoSpawnAllowed = false;
  d.nrLeftAllowedToSpawn = 0;
  d.isUnique = true;
  d.spawnMinLevel = 3;
  d.monsterLvl = 3;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_floor;
  d.description
  = "\"That object - no larger than a good sized rat and quaintly called by the townspeople, \"Brown Jenkin\" - seemed to have been the fruit of a remarkable case of sympathetic herd-delusion, for in 1692, no less than eleven persons had testified to glimpsing it. There were recent rumors, too, with a baffling and disconcerting amount of agreement. Witnesses said it had long hair and the shape of a rat, but that its sharp-toothed, bearded face was evilly human while its paws were like tiny human hands. It took messages betwixt old Keziah and the devil, and was nursed on the witch's blood, which it sucked like a vampire. Its voice was a kind of loathsome titter, and could speak all languages.\" H.P.Lovecraft -\"Dreams in the witch house\".";
  d.nrTurnsAwarePlayer = 999;
  d.erraticMovement = actorErratic_rare;
  d.shockValue = shockValue_some;
  d.isRat = true;
  setStrengthsFromFormula(d, normal);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Wolf";
  d.name_the = "The Wolf";
  d.moveType = moveType_walk;
  d.devName = actor_wolf;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.abilityValues.setAbilityValue(ability_dodgeAttack, 20);
  d.speed = actorSpeed_fast;
  d.rangedCooldownTurns = 0;
  d.glyph = 'd';
  d.color = clrGray;
  d.tile = tile_wolf;
  d.spawnMinLevel = 0;
  d.spawnMaxLevel = 10;
  d.monsterLvl = 2;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 5;
  d.description = "A large wolf with eyes full of cunning.";
  d.aggroTextMonsterSeen = d.name_the + " snarls at me.";
  d.aggroTextMonsterHidden = "I hear a wolf howl.";
  d.erraticMovement = actorErratic_somewhat;
  d.isCanine = true;
  d.canBeSummoned = true;
  setStrengthsFromFormula(d, normal);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Giant Bat";
  d.name_the = "The Giant Bat";
  d.moveType = moveType_fly;
  d.devName = actor_giantBat;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.abilityValues.setAbilityValue(ability_dodgeAttack, 75);
  d.speed = actorSpeed_fastest;
  d.rangedCooldownTurns = 0;
  d.glyph = 'B';
  d.color = clrGray;
  d.tile = tile_bat;
  d.spawnMinLevel = 4;
  d.monsterLvl = 4;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 5;
  d.description = "An unknown species, perhaps stemming from some hidden bowels of the earth. It is about as tall as a full-grown human.";
  d.erraticMovement = actorErratic_very;
  d.shockValue = shockValue_mild;
  d.canBeSummoned = true;
  setStrengthsFromFormula(d, normal);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Byakhee";
  d.name_the = "The Byakhee";
  d.moveType = moveType_fly;
  d.devName = actor_byakhee;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.abilityValues.setAbilityValue(ability_dodgeAttack, 40);
  d.speed = actorSpeed_fastest;
  d.rangedCooldownTurns = 0;
  d.glyph = 'B';
  d.color = clrBrownDark;
  d.tile = tile_byakhee;
  d.spawnMinLevel = 6;
  d.monsterLvl = 6;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 5;
  d.description
  = "\"There flapped rhythmically a horde of tame, trained, hybrid winged things ... not altogether crows, nor moles, nor buzzards, nor ants, nor decomposed humand beings, but something I cannot and must not recall.\"-H.P. Lovecraft, \"The Festival\". A Byakhee appears as a disturbing mixture of creatures composing a isHumanoid form. Insect traits vie with predatory birds, digging mammals, and possibly the necrotic flesh of human victims. At home in lonely voids of interstellar space, Byakhee are a created race, though their origin is buried in the distant past.";
  d.erraticMovement = actorErratic_somewhat;
  d.shockValue = shockValue_some;
  d.canBeSummoned = true;
  setStrengthsFromFormula(d, normal);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Fungi from Yuggoth";
  d.name_the = "The Fungi from Yuggoth";
  d.moveType = moveType_fly;
  d.devName = actor_miGo;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = false;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_fast;
  d.rangedCooldownTurns = 4;
  d.spellCooldownTurns = 4;
  d.glyph = 'E';
  d.color = clrMagentaLight;
  d.tile = tile_migo;
  d.spawnMinLevel = 4;
  d.monsterLvl = 4;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.canOpenDoors = true;
  d.nrTurnsAwarePlayer = 25;
  d.description
  = "Fungi are more closely related to animals than plants, so it's no wonder that on some worlds, fungal life evolved to dominate animal based intelligences. The mi-go, as they are called, come from such a world. More like crustaceans than any other terrestial life form, they find themselves somewhat hampered by our planet's thicker atmosphere and heavy gravity. They are a highly scientific race with great aptitude for surgery. Typical mi-go have heads like large exposed brains, with many convolutions on the wrinkled surfaces; six to eight limbs, a single pair of vast membranous wings, and a long semiprehensile tail trailing beind. They have visited Earth for centuries to mine certain minerals not available on their icy world, and more recently, to study its odd inhabitants. The mi-go are responsible for many \"alien abduction\" kidnappings. Physically they are not much more robust than the average human, they rely upon their superior science to subdue any primitives who stumble upon their mines and outposts.";
  d.spellCastMessage = "The Fungi makes strange gestures in the air.";
  d.erraticMovement = actorErratic_rare;
  d.shockValue = shockValue_mild;
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Ghoul";
  d.name_the = "The Ghoul";
  d.moveType = moveType_walk;
  d.devName = actor_ghoul;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.glyph = 'M';
  d.color = clrGreen;
  d.tile = tile_ghoul;
  d.spawnMinLevel = 5;
  d.monsterLvl = 5;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.canOpenDoors = true;
  d.nrTurnsAwarePlayer = 25;
  d.description
  = "\"These figures were seldom completely human, but often approached humanity in varying degrees. Most of the bodies, while roughly bipedal, had a forward slumping, and a vaguely canine cast. The texture of the majority was a kind of unpleasant rubberiness\" -H.P.Lovecraft \"Pickman's Model\". Ghouls are rubbery, loathsome isHumanoids with hooflike feet, canine features, and claws. They are often encrusted with grave mold collected as they feed.";
  d.erraticMovement = actorErratic_somewhat;
  d.shockValue = shockValue_heavy;
  setStrengthsFromFormula(d, normal);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Shadow";
  d.name_the = "The Shadow";
  d.moveType = moveType_walk;
  d.devName = actor_shadow;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = false;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 'M';
  d.color = clrGray;
  d.tile = tile_shadow;
  d.spawnMinLevel = 4;
  d.monsterLvl = 3;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = false;
  d.canOpenDoors = false;
  d.canBleed = false;
  d.canBeSummoned = true;
  d.deathMessageOverride = "The shadow fades.";
  d.nrTurnsAwarePlayer = 5;
  d.description = "A living shadow";
  d.isAutoDescriptionAllowed = false;
  d.erraticMovement = actorErratic_somewhat;
  d.shockValue = shockValue_heavy;
  setStrengthsFromFormula(d, weak);
  d.abilityValues.setAbilityValue(ability_stealth, 80);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Mummy";
  d.name_the = "The Mummy";
  d.moveType = moveType_walk;
  d.devName = actor_mummy;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 3;
  d.glyph = 'P';
  d.color = clrMagenta;
  d.tile = tile_mummy;
  d.spawnMinLevel = 7;
  d.monsterLvl = 7;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.canOpenDoors = true;
  d.nrTurnsAwarePlayer = 9999;
  d.description = "A mummified human being, possibly dating back millenia.";
  d.spellCastMessage = "The mummy casts a spell.";
  d.erraticMovement = actorErratic_rare;
  d.shockValue = shockValue_heavy;
  d.isUndead = true;
  d.isHumanoid = true;
  setStrengthsFromFormula(d, strong);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "Khephren";
  d.name_the = "Khephren";
  d.moveType = moveType_walk;
  d.devName = actor_khephren;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 5;
  d.isUnique = true;
  d.nrLeftAllowedToSpawn = 0;
  d.glyph = 'P';
  d.color = clrRed;
  d.tile = tile_mummy;
  d.isAutoSpawnAllowed = false;
  d.spawnMinLevel = 999;
  d.monsterLvl = 11;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.canOpenDoors = true;
  d.nrTurnsAwarePlayer = 9999;
  d.description
  = "The mummified fourth dynasty Egyptian pharaoh Khephren. How he came to dwell here is beyond my guess. His name means \"Rise, Ra!\"";
  d.spellCastMessage = "Khephren casts a spell.";
  d.erraticMovement = actorErratic_rare;
  d.shockValue = shockValue_heavy;
  d.isUndead = true;
  d.isHumanoid = true;
  setStrengthsFromFormula(d, strong);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "Nitokris";
  d.name_the = "Nitokris";
  d.moveType = moveType_walk;
  d.devName = actor_nitokris;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 5;
  d.isUnique = true;
  d.nrLeftAllowedToSpawn = 1;
  d.glyph = 'P';
  d.color = clrRedLight;
  d.tile = tile_mummy;
  d.spawnMinLevel = 11;
  d.monsterLvl = 11;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.canOpenDoors = true;
  d.nrTurnsAwarePlayer = 9999;
  d.description
  = "The mummified sixth dynasty Egyptian pharaoh Nitokris. How she came to dwell here is beyond my guess. Her name is found in the histories of Herodotus and writings of Manetho. According to the writings of the former, she took the throne by inviting her brothers murderers to a banquet. Then killed them by flooding the sealed room with the Nile.";
  d.spellCastMessage = "Nitokris casts a spell.";
  d.erraticMovement = actorErratic_rare;
  d.shockValue = shockValue_heavy;
  d.isUndead = true;
  d.isHumanoid = true;
  setStrengthsFromFormula(d, strong);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Deep One";
  d.name_the = "The Deep One";
  d.moveType = moveType_walk;
  d.devName = actor_deepOne;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 15;
  d.glyph = 'F';
  d.color = clrWhite;
  d.tile = tile_deepOne;
  d.spawnMinLevel = 6;
  d.monsterLvl = 6;
  d.groupSize = monsterGroupSize_horde;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canBashDoors = true;
  d.canOpenDoors = true;
  d.nrTurnsAwarePlayer = 20;
  d.description
  = "Deep ones are misbegotten creatures of the deep. A deep one appears as an abominable crossbreed of a human and amphibian. Its fins are merged with twisted arms and legs; its bent back is crowned with a long, spiny frill. They can breathe both air and water. In the timeless depths of the sea, the deep one's alien, arrogant lives are coldly beautiful, unbelievably cruel, and effectively immortal. Deep ones may be worshipped by humans with whom they regularly interbreed.";
  d.erraticMovement = actorErratic_rare;
  d.shockValue = shockValue_some;
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Mass of Worms";
  d.name_the = "The Mass of Worms";
  d.moveType = moveType_walk;
  d.devName = actor_wormMass;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = false;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 'w';
  d.color = clrWhite;
  d.tile = tile_massOfWorms;
  d.spawnMinLevel = 4;
  d.monsterLvl = 1;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 10;
  d.description = "A slithering conglomeration of carnivorous worms.";
  d.isAutoDescriptionAllowed = false;
  d.erraticMovement = actorErratic_very;
  d.canBleed = false;
  d.shockValue = shockValue_none;
  setStrengthsFromFormula(d, weak);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Fire Vampire";
  d.name_the = "The Fire Vampire";
  d.moveType = moveType_fly;
  d.devName = actor_fireVampire;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = false;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 'C';
  d.color = clrRed;
  d.tile = tile_fireVampire;
  d.isAutoSpawnAllowed = false;
  d.spawnMinLevel = 999;
  d.monsterLvl = 5;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.nrTurnsAwarePlayer = 5;
  d.nrLeftAllowedToSpawn = 0;
  d.isAutoDescriptionAllowed = false;
  d.canOpenDoors = false;
  d.canBashDoors = false;
  d.description
  = "A fire vampire is a mote of living flame. The core of a fire vampire appears as a blot of superheated plasma. When this core enters a suitable atmosphere, it flames and drips with fire.";
  d.canBleed = true;
  d.canBeSummoned = true;
  d.erraticMovement = actorErratic_rare;
  setStrengthsFromFormula(d, weak);
  d.shockValue = shockValue_mild;
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Gray Ooze";
  d.name_the = "The Gray Ooze";
  d.moveType = moveType_ooze;
  d.devName = actor_oozeGray;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_sluggish;
  d.rangedCooldownTurns = 0;
  d.glyph = 'o';
  d.color = clrGray;
  d.tile = tile_ooze;
  d.spawnMinLevel = 3;
  d.monsterLvl = 3;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 250;
  d.isAutoDescriptionAllowed = true;
  d.canOpenDoors = false;
  d.canBashDoors = false;
  d.description = "It's just a mass of gunk, but it seems sentient.";
  d.deathMessageOverride = "The Ooze disintegrates.";
  d.canBleed = false;
  d.canBeSummoned = true;
  setStrengthsFromFormula(d, superStrong);
  d.shockValue = shockValue_some;
  d.erraticMovement = actorErratic_somewhat;
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Clear Ooze";
  d.name_the = "The Clear Ooze";
  d.moveType = moveType_ooze;
  d.devName = actor_oozeClear;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_sluggish;
  d.rangedCooldownTurns = 0;
  d.glyph = 'o';
  d.color = clrWhiteHigh;
  d.tile = tile_ooze;
  d.spawnMinLevel = 4;
  d.monsterLvl = 4;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 250;
  d.isAutoDescriptionAllowed = true;
  d.canOpenDoors = false;
  d.canBashDoors = false;
  d.description = "It's a clear mass of gunk. They can be hard to spot.";
  d.deathMessageOverride = "The Ooze disintegrates.";
  d.canBleed = false;
  d.canBeSummoned = true;
  setStrengthsFromFormula(d, strong);
  d.shockValue = shockValue_some;
  d.erraticMovement = actorErratic_somewhat;
  d.abilityValues.setAbilityValue(ability_stealth, 100);
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Putrid Ooze";
  d.name_the = "The Putrid Ooze";
  d.moveType = moveType_ooze;
  d.devName = actor_oozePutrid;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_sluggish;
  d.rangedCooldownTurns = 0;
  d.glyph = 'o';
  d.color = clrGreenLight;
  d.tile = tile_ooze;;
  d.spawnMinLevel = 5;
  d.monsterLvl = 5;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 250;
  d.isAutoDescriptionAllowed = true;
  d.canOpenDoors = false;
  d.canBashDoors = false;
  d.description = "It's just a mass of gunk, but it seems sentient. It stinks like rotting cadavers.";
  d.deathMessageOverride = "The Ooze disintegrates.";
  d.canBleed = false;
  d.canBeSummoned = true;
  setStrengthsFromFormula(d, superStrong);
  d.erraticMovement = actorErratic_somewhat;
  d.shockValue = shockValue_some;
  finalizeDefinition(d);
  d.reset();

  d.name_a = "A Hunting Horror";
  d.name_the = "The Hunting Horror";
  d.moveType = moveType_fly;
  d.devName = actor_huntingHorror;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.attemptsAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = false;
  d.speed = actorSpeed_fastest;
  d.rangedCooldownTurns = 0;
  d.glyph = 'W';
  d.color = clrGray;
  d.tile = tile_huntingHorror;
  d.spawnMinLevel = LAST_CAVERN_LEVEL - 1;
  d.spawnMaxLevel = 99999;
  d.monsterLvl = 20;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.nrTurnsAwarePlayer = 2;
  d.isAutoDescriptionAllowed = true;
  d.canOpenDoors = false;
  d.canBashDoors = true;
  d.description
  = "It resembles an enormous black ropy worm, like a legless dragon seen in a nightmare. A great gaping maw filled with jagged, irregular teeth gapes open hungrily as it flies in search of prey. Hunting horrors haunt the dark places of the universe, from which they are called up at the whim of their lord Nyarlathotep.";
  d.canBleed = true;
  d.canBeSummoned = false;
  setStrengthsFromFormula(d, strong);
  d.shockValue = shockValue_heavy;
  d.erraticMovement = actorErratic_somewhat;
  finalizeDefinition(d);
  d.reset();
}

