#include <string>
#include <vector>
#include <math.h>

#include "ActorData.h"

#include "CommonTypes.h"
#include "Converters.h"
#include "Item.h"
#include "Engine.h"

using namespace std;

void ActorData::reset() {
  id = actor_empty;
  name_a = "";
  name_the = "";
  tile = tile_empty;
  glyph = 'X';
  color = clrYellow;
  groupSize = monsterGroupSize_alone;
  hp = dmgMelee = dmgRanged = 1;
  spi = 12;
  speed = actorSpeed_normal;
  bodyType = actorBodyType_normal;
  for(int i = 0; i < endOfPropIds; i++) {intrProps[i] = false;}
  rangedCooldownTurns = spellCooldownTurns = 0;
  abilityVals.reset();
  aiBehavior.reset();
  nrTurnsAwarePlayer = 0;
  spawnMinDLVL = spawnMaxDLVL = 999;
  actorSize = actorSize_humanoid;
  isHumanoid = false;
  isAutoDescriptionAllowed = true;
  deathMessageOverride = "";
  nrOfKills = 0;
  canOpenDoors = canBashDoors = false;
  canSeeInDarkness = false;
  nrLeftAllowedToSpawn = -1;
  isUnique = false;
  isAutoSpawnAllowed = true;
  spellCastMessage = "[SPELL MESSAGE HERE]";
  erraticMovement = actorErratic_rare;
  monsterShockLevel = monsterShockLevel_none;
  isRat = isCanine = isSpider = isUndead = isGhost = false;
  canBeSummoned = false;
  canBleed = true;
  canDodge = true;
  nativeRooms.resize(0);
  description = "";
  aggroTextMonsterSeen = "";
  aggroTextMonsterHidden = "";
}

void ActorDataHandler::addData(ActorData& d) {
  dataList[d.id] = d;
  d.description.resize(0);
}

//void ActorDataHandler::setStrengthsFromFormula(
//  ActorData& d, const EntityStrength_t hpStrength) const {
//  //----------------------------------------------- HP
//  const double HP_BASE_DB = 3.0;
//  const double HP_INCR_DB = 1.75;
//
//  const double EFFECTIVE_LEVEL_DB =
//    double(d.monsterLvl) + (d.isUnique ? 4.0 : 0.0);
//
//  const double HP_BEFORE_STRENGTH_DB =
//    HP_BASE_DB + (HP_INCR_DB * (EFFECTIVE_LEVEL_DB - 1));
//
//  const double STRENGTH_FACTOR =
//    EntityStrength::getFactor(hpStrength);
//
//  const int HP_AFTER_STRENGTH =
//    int(HP_BEFORE_STRENGTH_DB * STRENGTH_FACTOR);
//  const int HP_CAP = 999;
//  const int HP_AFTER_CAP = min(HP_CAP, HP_AFTER_STRENGTH);
//  d.hp = HP_AFTER_CAP;
//
//  //----------------------------------------------- ATTACK SKILL
//  const double ATTACK_BASE_DB = 14.0;
//  const double ATTACK_INCR_DB = 10.0;
//
//  const int ATTACK =
//    int(ceil(ATTACK_BASE_DB + ATTACK_INCR_DB * (EFFECTIVE_LEVEL_DB - 1.0)));
//
//  const int ATTACK_CAP = 40;
//  const int ATTACK_AFTER_CAP = min(ATTACK_CAP, ATTACK);
//
//  d.abilityVals.setVal(ability_accuracyMelee, ATTACK_AFTER_CAP);
//  d.abilityVals.setVal(ability_accuracyRanged, ATTACK_AFTER_CAP);
//
//  //----------------------------------------------- STATUS RESISTANCE
//  const double STATUS_RES_BASE = 5.0;
//  const double STATUS_RES_INCR = 3.0;
//
//  const int STATUS_RES =
//    int(ceil(STATUS_RES_BASE + STATUS_RES_INCR * (EFFECTIVE_LEVEL_DB - 1.0)));
//  d.abilityVals.setVal(ability_resistStatusBody, STATUS_RES);
//  d.abilityVals.setVal(ability_resistStatusMind, STATUS_RES);
//}

void ActorDataHandler::initDataList() {
  ActorData d;
  d.reset();
  addData(d);

  d.name_a = "Player";
  d.name_the = "Player";
  d.bodyType = actorBodyType_normal;
  d.id = actor_player;
  d.hp = 16;
  d.spi = 6;
  d.speed = actorSpeed_normal;
  d.glyph = '@';
  d.color = clrWhiteHigh;
  d.tile = tile_playerFirearm;
  d.isAutoSpawnAllowed = false;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  addData(d);
  d.reset();

  d.name_a = "A Reanimated Corpse";
  d.name_the = "The Reanimated Corpse";
  d.bodyType = actorBodyType_normal;
  d.id = actor_zombie;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.glyph = 'Z';
  d.color = clrBrown;
  d.tile = tile_zombieUnarmed;
  d.hp = 10;
  d.dmgMelee = 4;
  d.abilityVals.setVal(ability_accuracyMelee, 24);
  d.spawnMinDLVL = 1;
  d.spawnMaxDLVL = FIRST_CAVERN_LEVEL - 1;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canBashDoors = true;
  d.canSeeInDarkness = true;
  d.nrTurnsAwarePlayer = 12;
  d.description = "This rotting thing appears to have been brought back to life through some abominable process. It has grown sharp claws to attack with.";
  d.aggroTextMonsterSeen = d.name_the + " growls at me.";
  d.aggroTextMonsterHidden = "I hear a growling voice.";
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.isUndead = true;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_monster);
  d.nativeRooms.push_back(roomTheme_crypt);
  addData(d);
  d.reset();

  d.name_a = "A Reanimated Corpse";
  d.name_the = "The Reanimated Corpse";
  d.bodyType = actorBodyType_normal;
  d.id = actor_zombieAxe;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.glyph = 'Z';
  d.color = clrGray;
  d.tile = tile_zombieArmed;
  d.hp = 10;
  d.dmgMelee = 9;
  d.abilityVals.setVal(ability_accuracyMelee, 34);
  d.abilityVals.setVal(ability_accuracyRanged, 0);
  d.spawnMinDLVL = 2;
  d.spawnMaxDLVL = FIRST_CAVERN_LEVEL - 1;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canBashDoors = true;
  d.canSeeInDarkness = true;
  d.nrTurnsAwarePlayer = 10;
  d.description = "This rotting thing appears to have been brought back to life through some abominable process. It is wielding a rusty axe.";
  d.aggroTextMonsterSeen = d.name_the + " growls at me.";
  d.aggroTextMonsterHidden = "I hear a growling voice.";
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.isUndead = true;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_monster);
  d.nativeRooms.push_back(roomTheme_crypt);
  addData(d);
  d.reset();

  d.name_a = "A Bloated Corpse";
  d.name_the = "The Bloated Corpse";
  d.bodyType = actorBodyType_normal;
  d.id = actor_bloatedZombie;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 20;
  d.glyph = 'Z';
  d.color = clrWhiteHigh;
  d.tile = tile_zombieBloated;
  d.hp = 13;
  d.dmgMelee = 4;
  d.dmgRanged = 3;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.abilityVals.setVal(ability_accuracyRanged, 40);
  d.spawnMinDLVL = 3;
  d.spawnMaxDLVL = FIRST_CAVERN_LEVEL - 1;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canBashDoors = true;
  d.canSeeInDarkness = true;
  d.nrTurnsAwarePlayer = 50;
  d.description = "This lumbering giant corpse seems to be artificially bloated somehow. It is constantly oozing putrid liquid that it can spit to attack with.";
  d.aggroTextMonsterHidden = "I hear heavy footsteps.";
  d.erraticMovement = actorErratic_rare;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.isUndead = true;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_monster);
  d.nativeRooms.push_back(roomTheme_crypt);
  addData(d);
  d.reset();

  d.name_a = "Major Clapham-Lee";
  d.name_the = "Major Clapham-Lee";
  d.bodyType = actorBodyType_normal;
  d.id = actor_majorClaphamLee;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.glyph = 'Z';
  d.color = clrCyanLgt;
  d.tile = tile_zombieUnarmed;
  d.hp = 24;
  d.dmgMelee = 2;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.abilityVals.setVal(ability_accuracyRanged, 40);
  d.spawnMinDLVL = 4;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canBashDoors = true;
  d.canSeeInDarkness = true;
  d.nrTurnsAwarePlayer = 999;
  d.description = "Major Sir Eric Moreland Clapham-Lee was once a commanding officer during the Great War. Shortly after his plane was shot down, his body was stolen. Now he roams these halls as a resurrected warrior in service of the cult, commanding a squad of undead.";
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_terrifying;
  d.isUndead = true;
  d.isUnique = true;
  d.nrLeftAllowedToSpawn = 1;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_monster);
  d.nativeRooms.push_back(roomTheme_crypt);
  addData(d);
  d.reset();

  d.name_a = "Dean Halsey";
  d.name_the = "Dean Halsey";
  d.bodyType = actorBodyType_normal;
  d.id = actor_deanHalsey;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.glyph = 'Z';
  d.color = clrCyan;
  d.tile = tile_zombieUnarmed;
  d.hp = 24;
  d.dmgMelee = 2;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.abilityVals.setVal(ability_accuracyRanged, 40);
  d.isAutoSpawnAllowed = false;
  d.spawnMinDLVL = 4;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canBashDoors = true;
  d.canSeeInDarkness = true;
  d.nrTurnsAwarePlayer = 999;
  d.description = "Alan Halsey was the dean of the Miskatonic University in New England. Somehow he must have gotten into the hands of the Cult, who turned him into the hellish zombie warrior I now see before me.";
  d.erraticMovement = actorErratic_rare;
  d.monsterShockLevel = monsterShockLevel_terrifying;
  d.isUndead = true;
  d.isUnique = true;
  d.nrLeftAllowedToSpawn = 0;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_monster);
  d.nativeRooms.push_back(roomTheme_crypt);
  addData(d);
  d.reset();

  d.name_a = "A Cultist";
  d.name_the = "The Cultist";
  d.bodyType = actorBodyType_normal;
  d.id = actor_cultist;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 3;
  d.spellCooldownTurns = 4;
  d.glyph = 'P';
  d.color = clrGray;
  d.tile = tile_cultistFirearm;
  d.hp = 4;
  d.spi = 12;
  d.abilityVals.setVal(ability_accuracyMelee, 34);
  d.abilityVals.setVal(ability_accuracyRanged, 34);
  d.spawnMinDLVL = 1;
  d.spawnMaxDLVL = FIRST_CAVERN_LEVEL - 1;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canOpenDoors = true;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 25;
  d.description = "A fanatic cultist of the lowest rank, madly gibbering in some half-lost language.";
  d.spellCastMessage = "The accolyte makes strange gestures in the air.";
  d.erraticMovement = actorErratic_rare;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_human);
  d.nativeRooms.push_back(roomTheme_ritual);
  addData(d);
  d.reset();

  d.name_a = "A Cultist";
  d.name_the = "The Cultist";
  d.bodyType = actorBodyType_normal;
  d.id = actor_cultistTeslaCannon;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 3;
  d.spellCooldownTurns = 4;
  d.glyph = 'P';
  d.color = clrYellow;
  d.tile = tile_cultistFirearm;
  d.hp = 5;
  d.spi = 12;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.abilityVals.setVal(ability_accuracyRanged, 40);
  d.spawnMinDLVL = 7;
  d.spawnMaxDLVL = FIRST_CAVERN_LEVEL - 1;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canOpenDoors = true;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 25;
  d.description = "A fanatic cultist of the lowest rank, madly gibbering in some half-lost language. It is wielding a Tesla Cannon.";
  d.spellCastMessage = "The accolyte makes strange gestures in the air.";
  d.erraticMovement = actorErratic_rare;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_human);
  d.nativeRooms.push_back(roomTheme_ritual);
  addData(d);
  d.reset();

  d.name_a = "A Cultist";
  d.name_the = "The Cultist";
  d.bodyType = actorBodyType_normal;
  d.id = actor_cultistSpikeGun;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 3;
  d.spellCooldownTurns = 4;
  d.glyph = 'P';
  d.color = clrBlueLgt;
  d.tile = tile_cultistFirearm;
  d.hp = 6;
  d.spi = 12;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.abilityVals.setVal(ability_accuracyRanged, 40);
  d.spawnMinDLVL = 4;
  d.spawnMaxDLVL = FIRST_CAVERN_LEVEL - 1;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canOpenDoors = true;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 25;
  d.description = "A fanatic cultist of the lowest rank, madly gibbering in some half-lost language. It is wielding a Spike gun.";
  d.spellCastMessage = "The accolyte makes strange gestures in the air.";
  d.erraticMovement = actorErratic_rare;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_human);
  d.nativeRooms.push_back(roomTheme_ritual);
  addData(d);
  d.reset();

  d.name_a = "Keziah Mason";
  d.name_the = "Keziah Mason";
  d.bodyType = actorBodyType_normal;
  d.id = actor_keziahMason;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 2;
  d.glyph = 'P';
  d.color = clrMagenta;
  d.tile = tile_witchOrWarlock;
  d.hp = 10;
  d.spi = 40;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.abilityVals.setVal(ability_accuracyRanged, 40);
  d.nrLeftAllowedToSpawn = 1;
  d.isUnique = true;
  d.canSeeInDarkness = true;
  d.spawnMinDLVL = 3;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.description = "During the Salem witch trials of 1692 an old woman by the name of Keziah Mason was arrested for her suspicious behavior and seeming insight into other worlds. In her testimony to the judge, she confessed to having signed her name in the Black Book of Azathoth, and of her secret name of Nahab. She later disappeared mysteriously from Salem. She is described as having a \"bent back, long nose, and shrivelled chin\" and has a \"croaking voice\". She has an animal familier; the rat Brown Jenkin, which she trusts to carry messages between her and the devil. She feeds this creature on her blood.";
  d.spellCastMessage = "Keziah makes strange gestures in the air.";
  d.aggroTextMonsterSeen = d.name_the + " chortles at me in a croaking voice.";
  d.aggroTextMonsterHidden = "I hear a repulsive croaking voice.";
  d.nrTurnsAwarePlayer = 999;
  d.erraticMovement = actorErratic_rare;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_ritual);
  addData(d);
  d.reset();

  d.name_a = "Brown Jenkin";
  d.name_the = "Brown Jenkin";
  d.bodyType = actorBodyType_normal;
  d.id = actor_brownJenkin;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.glyph = 'r';
  d.color = clrBrownDark;
  d.tile = tile_ratThing;
  d.hp = 15;
  d.dmgMelee = 3;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.isAutoSpawnAllowed = false;
  d.nrLeftAllowedToSpawn = 0;
  d.isUnique = true;
  d.canSeeInDarkness = true;
  d.spawnMinDLVL = dataList[actor_keziahMason].spawnMinDLVL;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_floor;
  d.description = "\"That object - no larger than a good sized rat and quaintly called by the townspeople, \"Brown Jenkin\" - seemed to have been the fruit of a remarkable case of sympathetic herd-delusion, for in 1692, no less than eleven persons had testified to glimpsing it. There were recent rumors, too, with a baffling and disconcerting amount of agreement. Witnesses said it had long hair and the shape of a rat, but that its sharp-toothed, bearded face was evilly human while its paws were like tiny human hands. It took messages betwixt old Keziah and the devil, and was nursed on the witch's blood, which it sucked like a vampire. Its voice was a kind of loathsome titter, and could speak all languages.\" H.P.Lovecraft -\"Dreams in the witch house\".";
  d.aggroTextMonsterSeen = d.name_the + " titters at me in a loathsome voice.";
  d.aggroTextMonsterHidden = "I hear a loathsome titter.";
  d.nrTurnsAwarePlayer = 999;
  d.erraticMovement = actorErratic_rare;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.isRat = true;
  addData(d);
  d.reset();

//  d.name_a = "The Lord of Pestilence";
//  d.name_the = "The Lord of Pestilence";
//  d.bodyType = actorBodyType_normal;
//  d.id = actor_lordOfPestilence;
//  d.aiBehavior.looks = true;
//  d.aiBehavior.makesRoomForFriend = false;
//  d.aiBehavior.pathsToTargetWhenAware = true;
//  d.aiBehavior.movesTowardTargetWhenVision = true;
//  d.aiBehavior.movesTowardLair = false;
//  d.aiBehavior.movesTowardLeader = true;
//  d.speed = actorSpeed_normal;
//  d.rangedCooldownTurns = 0;
//  d.spellCooldownTurns = 2;
//  d.glyph = 'P';
//  d.color = clrRedLgt;
//  d.tile = tile_witchOrWarlock;
//  d.nrLeftAllowedToSpawn = 0;
//  d.isUnique = true;
//  d.canSeeInDarkness = true;
//  d.spawnMinDLVL = 100;
//  d.monsterLvl = 15;
//  d.groupSize = monsterGroupSize_alone;
//  d.actorSize = actorSize_humanoid;
//  d.isHumanoid = true;
//  d.description = "Asdf";
//  d.spellCastMessage = "The Lord of Pestilence makes strange gestures in the air.";
//  d.nrTurnsAwarePlayer = 999;
//  d.erraticMovement = actorErratic_rare;
//  d.monsterShockLevel = monsterShockLevel_scary;
//  setStrengthsFromFormula(d, weak);
//  addData(d);
//  d.reset();

//  d.name_a = "The Lord of Shadows";
//  d.name_the = "The Lord of Shadows";
//  d.bodyType = actorBodyType_normal;
//  d.id = actor_lordOfShadows;
//  d.aiBehavior.looks = true;
//  d.aiBehavior.makesRoomForFriend = false;
//  d.aiBehavior.pathsToTargetWhenAware = true;
//  d.aiBehavior.movesTowardTargetWhenVision = true;
//  d.aiBehavior.movesTowardLair = false;
//  d.aiBehavior.movesTowardLeader = true;
//  d.speed = actorSpeed_normal;
//  d.rangedCooldownTurns = 0;
//  d.spellCooldownTurns = 2;
//  d.glyph = 'P';
//  d.color = clrRedLgt;
//  d.tile = tile_witchOrWarlock;
//  d.nrLeftAllowedToSpawn = 0;
//  d.isUnique = true;
//  d.canSeeInDarkness = true;
//  d.spawnMinDLVL = 100;
//  d.monsterLvl = 15;
//  d.groupSize = monsterGroupSize_alone;
//  d.actorSize = actorSize_humanoid;
//  d.isHumanoid = true;
//  d.description = "Asdf";
//  d.spellCastMessage = "The Lord of Shadows makes strange gestures in the air.";
//  d.nrTurnsAwarePlayer = 999;
//  d.erraticMovement = actorErratic_rare;
//  d.monsterShockLevel = monsterShockLevel_scary;
//  setStrengthsFromFormula(d, weak);
//  d.abilityVals.setVal(ability_stealth, 90);
//  addData(d);
//  d.reset();

//  d.name_a = "The Lord of Spiders";
//  d.name_the = "The Lord of Spiders";
//  d.bodyType = actorBodyType_normal;
//  d.id = actor_lordOfSpiders;
//  d.aiBehavior.looks = true;
//  d.aiBehavior.makesRoomForFriend = false;
//  d.aiBehavior.pathsToTargetWhenAware = true;
//  d.aiBehavior.movesTowardTargetWhenVision = true;
//  d.aiBehavior.movesTowardLair = false;
//  d.aiBehavior.movesTowardLeader = true;
//  d.speed = actorSpeed_normal;
//  d.rangedCooldownTurns = 0;
//  d.spellCooldownTurns = 2;
//  d.glyph = 'P';
//  d.color = clrRedLgt;
//  d.tile = tile_witchOrWarlock;
//  d.nrLeftAllowedToSpawn = 0;
//  d.isUnique = true;
//  d.canSeeInDarkness = true;
//  d.spawnMinDLVL = 100;
//  d.monsterLvl = 15;
//  d.groupSize = monsterGroupSize_alone;
//  d.actorSize = actorSize_humanoid;
//  d.isHumanoid = true;
//  d.description = "Asdf";
//  d.spellCastMessage = "The Lord of Spiders makes strange gestures in the air.";
//  d.nrTurnsAwarePlayer = 999;
//  d.erraticMovement = actorErratic_rare;
//  d.monsterShockLevel = monsterShockLevel_scary;
//  setStrengthsFromFormula(d, weak);
//  addData(d);
//  d.reset();

//  d.name_a = "The Lord of Spirits";
//  d.name_the = "The Lord of Spirits";
//  d.bodyType = actorBodyType_ethereal;
//  d.id = actor_lordOfSpirits;
//  d.aiBehavior.looks = true;
//  d.aiBehavior.makesRoomForFriend = false;
//  d.aiBehavior.pathsToTargetWhenAware = true;
//  d.aiBehavior.movesTowardTargetWhenVision = true;
//  d.aiBehavior.movesTowardLair = false;
//  d.aiBehavior.movesTowardLeader = true;
//  d.speed = actorSpeed_normal;
//  d.rangedCooldownTurns = 0;
//  d.spellCooldownTurns = 2;
//  d.glyph = 'P';
//  d.color = clrRedLgt;
//  d.tile = tile_witchOrWarlock;
//  d.nrLeftAllowedToSpawn = 0;
//  d.isUnique = true;
//  d.canSeeInDarkness = true;
//  d.spawnMinDLVL = 100;
//  d.monsterLvl = 15;
//  d.groupSize = monsterGroupSize_alone;
//  d.actorSize = actorSize_humanoid;
//  d.isHumanoid = true;
//  d.description = "Asdf";
//  d.spellCastMessage = "The Lord of Spirits makes strange gestures in the air.";
//  d.nrTurnsAwarePlayer = 999;
//  d.erraticMovement = actorErratic_rare;
//  d.monsterShockLevel = monsterShockLevel_scary;
//  setStrengthsFromFormula(d, weak);
//  addData(d);
//  d.reset();

  d.name_a = "A Cultist Priest";
  d.name_the = "The Cultist Priest";
  d.bodyType = actorBodyType_normal;
  d.id = actor_cultistPriest;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 2;
  d.glyph = 'P';
  d.color = clrCyanLgt;
  d.tile = tile_cultistDagger;
  d.hp = 6;
  d.spi = 20;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.spawnMinDLVL = 5;
  d.spawnMaxDLVL = FIRST_CAVERN_LEVEL - 1;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canOpenDoors = true;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 25;
  d.description = "A fanatic cultist of the priest rank, madly gibbering in some half-lost language.";
  d.spellCastMessage = "The priest makes strange gestures in the air.";
  d.erraticMovement = actorErratic_rare;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_human);
  d.nativeRooms.push_back(roomTheme_ritual);
  addData(d);
  d.reset();

  d.name_a = "A Green Spider";
  d.name_the = "The Green Spider";
  d.bodyType = actorBodyType_normal;
  d.id = actor_greenSpider;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 's';
  d.color = clrGreenLgt;
  d.tile = tile_spider;
  d.hp = 2;
  d.dmgMelee = 1;
  d.abilityVals.setVal(ability_accuracyMelee, 14);
  d.spawnMinDLVL = 1;
  d.spawnMaxDLVL = d.spawnMinDLVL + 5;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 5;
  d.description = "A large green spider.";
  d.erraticMovement = actorErratic_somewhat;
  d.isSpider = true;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_spider);
  addData(d);
  d.reset();

  d.name_a = "A White Spider";
  d.name_the = "The White Spider";
  d.bodyType = actorBodyType_normal;
  d.id = actor_whiteSpider;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 's';
  d.color = clrWhiteHigh;
  d.tile = tile_spider;
  d.hp = 2;
  d.dmgMelee = 1;
  d.abilityVals.setVal(ability_accuracyMelee, 14);
  d.spawnMinDLVL = 1;
  d.spawnMaxDLVL = d.spawnMinDLVL + 5;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_group;
  d.nrTurnsAwarePlayer = 5;
  d.actorSize = actorSize_floor;
  d.description = "A large white spider.";
  d.erraticMovement = actorErratic_somewhat;
  d.isSpider = true;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_spider);
  addData(d);
  d.reset();

  d.name_a = "A Red Spider";
  d.name_the = "The Red Spider";
  d.bodyType = actorBodyType_normal;
  d.id = actor_redSpider;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 's';
  d.color = clrRedLgt;
  d.tile = tile_spider;
  d.hp = 3;
  d.dmgMelee = 2;
  d.abilityVals.setVal(ability_accuracyMelee, 24);
  d.spawnMinDLVL = 2;
  d.spawnMaxDLVL = d.spawnMinDLVL + 5;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_group;
  d.nrTurnsAwarePlayer = 5;
  d.actorSize = actorSize_floor;
  d.description = "A large red spider.";
  d.erraticMovement = actorErratic_somewhat;
  d.isSpider = true;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_spider);
  addData(d);
  d.reset();

  d.name_a = "A Shadow Spider";
  d.name_the = "The Shadow Spider";
  d.bodyType = actorBodyType_normal;
  d.id = actor_shadowSpider;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 's';
  d.color = clrGray;
  d.tile = tile_spiderLeng;
  d.hp = 8;
  d.dmgMelee = 3;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.abilityVals.setVal(ability_stealth, 90);
  d.intrProps[propLightSensitive] = true;
  d.spawnMinDLVL = 6;
  d.spawnMaxDLVL = FIRST_CAVERN_LEVEL - 1;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_group;
  d.nrTurnsAwarePlayer = 5;
  d.actorSize = actorSize_humanoid;
  d.isSpider = true;
  d.description = "A faint shadow of a huge spider, lurking in my periphery.";
  d.erraticMovement = actorErratic_somewhat;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_spider);
  addData(d);
  d.reset();

  d.name_a = "A Leng Spider";
  d.name_the = "The Leng Spider";
  d.bodyType = actorBodyType_normal;
  d.id = actor_lengSpider;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_fast;
  d.rangedCooldownTurns = 0;
  d.glyph = 'S';
  d.color = clrMagenta;
  d.tile = tile_spiderLeng;
  d.hp = 30;
  d.dmgMelee = 8;
//  d.dmgRanged = 1;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
//  d.abilityVals.setVal(ability_accuracyRanged, 40);
  d.spawnMinDLVL = 10;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_few;
  d.nrTurnsAwarePlayer = 20;
  d.actorSize = actorSize_giant;
  d.description = "Leng spiders are huge, purplish arachnids, with pustulent bloated bodies and long, bristly legs. Native to the Dreamlands, the spiders of Leng are intelligent, dangerous, and gigantic.";
  d.erraticMovement = actorErratic_somewhat;
  d.isSpider = true;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_spider);
  addData(d);
  d.reset();

  d.name_a = "A Fire hound";
  d.name_the = "The Fire hound";
  d.bodyType = actorBodyType_normal;
  d.id = actor_fireHound;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_fast;
  d.rangedCooldownTurns = 6;
  d.glyph = 'd';
  d.color = clrRed;
  d.tile = tile_hound;
  d.hp = 13;
  d.dmgMelee = 4;
  d.dmgRanged = 4;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.abilityVals.setVal(ability_accuracyRanged, 60);
  d.abilityVals.setVal(ability_dodgeAttack, 35);
  d.intrProps[propRFire] = true;
  d.spawnMinDLVL = 9;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_floor;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 25;
  d.description = "This extremely aggressive canine seems to be part corporeal and part fire. It breathes searing flames.";
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.isCanine = true;
  d.canBeSummoned = true;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_monster);
  addData(d);
  d.reset();

  d.name_a = "A Ghost";
  d.name_the = "The Ghost";
  d.bodyType = actorBodyType_ethereal;
  d.id = actor_ghost;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 'G';
  d.color = clrGray;
  d.tile = tile_ghost;
  d.hp = 4;
  d.spi = 12;
  d.dmgMelee = 2;
  d.abilityVals.setVal(ability_accuracyMelee, 34);
  d.spawnMinDLVL = 3;
  d.spawnMaxDLVL = d.spawnMinDLVL + 5;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.nrTurnsAwarePlayer = 5;
  d.description = "A restless spirit?";
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_terrifying;
  d.isUndead = true;
  d.isGhost = true;
  d.canBeSummoned = true;
  d.deathMessageOverride = "The Ghost is put to rest.";
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_crypt);
  addData(d);
  d.reset();

  d.name_a = "A Phantasm";
  d.name_the = "The Phantasm";
  d.bodyType = actorBodyType_ethereal;
  d.id = actor_phantasm;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_fast;
  d.rangedCooldownTurns = 0;
  d.glyph = 'G';
  d.color = clrWhite;
  d.tile = tile_phantasm;
  d.hp = 9;
  d.spi = 12;
  d.dmgMelee = 6;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.spawnMinDLVL = 7;
  d.spawnMaxDLVL = d.spawnMinDLVL + 5;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.nrTurnsAwarePlayer = 7;
  d.description = "It exists between the land of the dead and the living. It resembles a grim reaper, including the cloak, scythe, and skeletal appearance.";
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_terrifying;
  d.isUndead = true;
  d.isGhost = true;
  d.canBeSummoned = true;
  d.deathMessageOverride = "The Phantasm is put to rest.";
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_crypt);
  addData(d);
  d.reset();

  d.name_a = "A Wraith";
  d.name_the = "The Wraith";
  d.bodyType = actorBodyType_ethereal;
  d.id = actor_wraith;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_fast;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 4;
  d.glyph = 'G';
  d.color = clrRed;
  d.tile = tile_wraith;
  d.hp = 15;
  d.spi = 20;
  d.dmgMelee = 6;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.spawnMinDLVL = 12;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_alone;
  d.spellCastMessage = "The Wraith casts a spell.";
  d.actorSize = actorSize_humanoid;
  d.nrTurnsAwarePlayer = 5;
  d.description = "A powerful spirit.";
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_terrifying;
  d.isUndead = true;
  d.isGhost = true;
  d.canBeSummoned = true;
  d.deathMessageOverride = "The Wraith is put to rest.";
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_crypt);
  addData(d);
  d.reset();

  d.name_a = "A Rat";
  d.name_the = "The Rat";
  d.bodyType = actorBodyType_normal;
  d.id = actor_rat;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = false;
  d.speed = actorSpeed_sluggish;
  d.rangedCooldownTurns = 0;
  d.glyph = 'r';
  d.color = clrGray;
  d.tile = tile_rat;
  d.hp = 2;
  d.spi = 1;
  d.dmgMelee = 1;
  d.abilityVals.setVal(ability_accuracyMelee, 14);
  d.spawnMinDLVL = 1;
  d.spawnMaxDLVL = d.spawnMinDLVL + 5;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_horde;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 5;
  d.description = "A large and aggressive rodent.";
  d.erraticMovement = actorErratic_somewhat;
  d.isRat = true;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_monster);
  d.nativeRooms.push_back(roomTheme_human);
  d.nativeRooms.push_back(roomTheme_crypt);
//  d.nativeRooms.push_back(roomTheme_chasm);
  addData(d);
  d.reset();

  d.name_a = "A Rat-thing";
  d.name_the = "The Rat-thing";
  d.bodyType = actorBodyType_normal;
  d.id = actor_ratThing;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = false;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 'r';
  d.color = clrBrown;
  d.tile = tile_ratThing;
  d.hp = 4;
  d.spi = 4;
  d.dmgMelee = 2;
  d.abilityVals.setVal(ability_accuracyMelee, 14);
  d.spawnMinDLVL = 2;
  d.spawnMaxDLVL = d.spawnMinDLVL + 5;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_horde;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 5;
  d.description = "At first sight, a Rat-thing can easily be mistaken for a large, dark rat. On closer examination, however, their human hands and evil caricatures of human heads reveal their unnatural nature. Rat-things are said to be created from dead cultists by foul witchcraft. Thus, they are found where the witch who created them had her lair.";
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_unsettling;
  d.isRat = true;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_monster);
  d.nativeRooms.push_back(roomTheme_human);
  d.nativeRooms.push_back(roomTheme_crypt);
//  d.nativeRooms.push_back(roomTheme_chasm);
  addData(d);
  d.reset();

  d.name_a = "A Wolf";
  d.name_the = "The Wolf";
  d.bodyType = actorBodyType_normal;
  d.id = actor_wolf;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_fast;
  d.rangedCooldownTurns = 0;
  d.glyph = 'd';
  d.color = clrGray;
  d.tile = tile_wolf;
  d.hp = 4;
  d.spi = 2;
  d.dmgMelee = 3;
  d.abilityVals.setVal(ability_accuracyMelee, 35);
  d.abilityVals.setVal(ability_dodgeAttack, 20);
  d.canSeeInDarkness = true;
  d.spawnMinDLVL = 0;
  d.spawnMaxDLVL = 10;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 5;
  d.description = "A large wolf with eyes full of cunning.";
  d.aggroTextMonsterSeen = d.name_the + " snarls at me.";
  d.aggroTextMonsterHidden = "I hear a wolf howl.";
  d.erraticMovement = actorErratic_somewhat;
  d.isCanine = true;
  d.canBeSummoned = true;
  d.nativeRooms.push_back(roomTheme_plain);
  addData(d);
  d.reset();

  d.name_a = "A Giant Bat";
  d.name_the = "The Giant Bat";
  d.bodyType = actorBodyType_flying;
  d.id = actor_giantBat;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_fastest;
  d.glyph = 'B';
  d.color = clrGray;
  d.tile = tile_bat;
  d.hp = 8;
  d.spi = 6;
  d.dmgMelee = 2;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.abilityVals.setVal(ability_dodgeAttack, 75);
  d.spawnMinDLVL = 4;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 5;
  d.description = "An unknown species, perhaps stemming from some hidden bowels of the earth. It is about as tall as a full-grown human.";
  d.aggroTextMonsterHidden = "I hear the flapping of great wings.";
  d.erraticMovement = actorErratic_very;
  d.monsterShockLevel = monsterShockLevel_unsettling;
  d.canBeSummoned = true;
  d.nativeRooms.push_back(roomTheme_plain);
//  d.nativeRooms.push_back(roomTheme_chasm);
  addData(d);
  d.reset();

  d.name_a = "A Byakhee";
  d.name_the = "The Byakhee";
  d.bodyType = actorBodyType_flying;
  d.id = actor_byakhee;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_fastest;
  d.glyph = 'B';
  d.color = clrBrownDark;
  d.tile = tile_byakhee;
  d.hp = 11;
  d.spi = 20;
  d.dmgMelee = 3;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.abilityVals.setVal(ability_accuracyRanged, 40);
  d.abilityVals.setVal(ability_dodgeAttack, 40);
  d.spawnMinDLVL = 6;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 5;
  d.description = "\"There flapped rhythmically a horde of tame, trained, hybrid winged things ... not altogether crows, nor moles, nor buzzards, nor ants, nor decomposed humand beings, but something I cannot and must not recall.\"-H.P. Lovecraft, \"The Festival\". A Byakhee appears as a disturbing mixture of creatures composing a humanoid form. Insect traits vie with predatory birds, digging mammals, and possibly the necrotic flesh of human victims. At home in lonely voids of interstellar space, Byakhee are a created race, though their origin is buried in the distant past.";
  d.aggroTextMonsterHidden = "I hear the flapping of great wings.";
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.canBeSummoned = true;
  d.nativeRooms.push_back(roomTheme_plain);
//  d.nativeRooms.push_back(roomTheme_chasm);
  addData(d);
  d.reset();

  d.name_a = "A Giant Mantis";
  d.name_the = "The Giant Mantis";
  d.bodyType = actorBodyType_normal;
  d.id = actor_giantMantis;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_fastest;
  d.glyph = 'I';
  d.color = clrGreenLgt;
  d.tile = tile_mantis;
  d.hp = 15;
  d.spi = 20;
  d.dmgMelee = 7;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.abilityVals.setVal(ability_dodgeAttack, 40);
  d.abilityVals.setVal(ability_stealth, 20);
  d.spawnMinDLVL = 8;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.nrTurnsAwarePlayer = 5;
  d.description = "A huge predatory insect.";
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_unsettling;
  d.canBeSummoned = false;
  d.nativeRooms.push_back(roomTheme_plain);
  addData(d);
  d.reset();

  d.name_a = "A Giant Locust";
  d.name_the = "The Giant Locust";
  d.bodyType = actorBodyType_flying;
  d.id = actor_giantLocust;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_fastest;
  d.glyph = 'I';
  d.color = clrBrown;
  d.tile = tile_locust;
  d.hp = 3;
  d.spi = 2;
  d.dmgMelee = 1;
  d.abilityVals.setVal(ability_accuracyMelee, 24);
  d.spawnMinDLVL = 7;
  d.spawnMaxDLVL = FIRST_CAVERN_LEVEL;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_swarm;
  d.actorSize = actorSize_floor;
  d.canBashDoors = false;
  d.nrTurnsAwarePlayer = 12;
  d.description = "A huge swarming insect. They breed rapidly.";
  d.erraticMovement = actorErratic_very;
  d.monsterShockLevel = monsterShockLevel_none;
  d.canBeSummoned = false;
  d.nativeRooms.push_back(roomTheme_plain);
  addData(d);
  d.reset();

  d.name_a = "A Fungi from Yuggoth";
  d.name_the = "The Fungi from Yuggoth";
  d.bodyType = actorBodyType_flying;
  d.id = actor_miGo;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = false;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_fast;
  d.rangedCooldownTurns = 3;
  d.spellCooldownTurns = 3;
  d.glyph = 'E';
  d.color = clrMagenta;
  d.tile = tile_migo;
  d.hp = 6;
  d.spi = 20;
  d.dmgRanged = 5;
  d.abilityVals.setVal(ability_accuracyMelee, 50);
  d.abilityVals.setVal(ability_accuracyRanged, 50);
  d.spawnMinDLVL = 6;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.canOpenDoors = true;
  d.nrTurnsAwarePlayer = 25;
  d.description = "Fungi are more closely related to animals than plants, so it's no wonder that on some worlds, fungal life evolved to dominate animal based intelligences. The mi-go, as they are called, come from such a world. More like crustaceans than any other terrestial life form, they find themselves somewhat hampered by our planet's thicker atmosphere and heavy gravity. They are a highly scientific race with great aptitude for surgery. Typical mi-go have heads like large exposed brains, with many convolutions on the wrinkled surfaces; six to eight limbs, a single pair of vast membranous wings, and a long semiprehensile tail trailing beind. They have visited Earth for centuries to mine certain minerals not available on their icy world, and more recently, to study its odd inhabitants. The mi-go are responsible for many \"alien abduction\" kidnappings. Physically they are not much more robust than the average human, they rely upon their superior science to subdue any primitives who stumble upon their mines and outposts.";
  d.spellCastMessage = "The Fungi makes strange gestures in the air.";
  d.aggroTextMonsterSeen = d.name_the + " speaks at me in a droning voice.";
  d.aggroTextMonsterHidden = "I hear a droning voice.";
  d.erraticMovement = actorErratic_rare;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.nativeRooms.push_back(roomTheme_plain);
//  d.nativeRooms.push_back(roomTheme_chasm);
  addData(d);
  d.reset();

  d.name_a = "A Ghoul";
  d.name_the = "The Ghoul";
  d.bodyType = actorBodyType_normal;
  d.id = actor_ghoul;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.glyph = 'M';
  d.color = clrGreen;
  d.tile = tile_ghoul;
  d.hp = 10;
  d.spi = 20;
  d.dmgMelee = 3;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.spawnMinDLVL = 5;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.canOpenDoors = true;
  d.nrTurnsAwarePlayer = 25;
  d.description = "\"These figures were seldom completely human, but often approached humanity in varying degrees. Most of the bodies, while roughly bipedal, had a forward slumping, and a vaguely canine cast. The texture of the majority was a kind of unpleasant rubberiness\" -H.P.Lovecraft \"Pickman's Model\". Ghouls are rubbery, loathsome humanoids with hooflike feet, canine features, and claws. They are often encrusted with grave mold collected as they feed.";
  d.aggroTextMonsterSeen = d.name_the + " howls at me.";
  d.aggroTextMonsterHidden = "I hear a chilling howl.";
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_terrifying;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_monster);
  addData(d);
  d.reset();

  d.name_a = "A Shadow";
  d.name_the = "The Shadow";
  d.bodyType = actorBodyType_normal;
  d.id = actor_shadow;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = false;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 'M';
  d.color = clrGray;
  d.tile = tile_shadow;
  d.hp = 4;
  d.spi = 12;
  d.dmgMelee = 2;
  d.abilityVals.setVal(ability_accuracyMelee, 34);
  d.abilityVals.setVal(ability_stealth, 90);
  d.intrProps[propLightSensitive] = true;
  d.spawnMinDLVL = 4;
  d.spawnMaxDLVL = d.spawnMinDLVL + 5;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = false;
  d.canOpenDoors = false;
  d.canBleed = false;
  d.canBeSummoned = true;
  d.deathMessageOverride = "The shadow fades.";
  d.nrTurnsAwarePlayer = 25;
  d.description = "A living shadow";
  d.isAutoDescriptionAllowed = false;
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.nativeRooms.push_back(roomTheme_monster);
  d.nativeRooms.push_back(roomTheme_plain);
  addData(d);
  d.reset();

  d.name_a = "A Mummy";
  d.name_the = "The Mummy";
  d.bodyType = actorBodyType_normal;
  d.id = actor_mummy;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 3;
  d.glyph = 'P';
  d.color = clrMagenta;
  d.tile = tile_mummy;
  d.hp = 21;
  d.spi = 30;
  d.dmgMelee = 6;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.spawnMinDLVL = 7;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.canOpenDoors = true;
  d.nrTurnsAwarePlayer = 9999;
  d.description = "A mummified human being, possibly dating back millenia.";
  d.spellCastMessage = "The mummy casts a spell.";
  d.erraticMovement = actorErratic_rare;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.isUndead = true;
  d.isHumanoid = true;
  d.nativeRooms.push_back(roomTheme_plain);
  addData(d);
  d.reset();

  d.name_a = "Khephren";
  d.name_the = "Khephren";
  d.bodyType = actorBodyType_normal;
  d.id = actor_khephren;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 3;
  d.isUnique = true;
  d.nrLeftAllowedToSpawn = 0;
  d.glyph = 'P';
  d.color = clrRed;
  d.tile = tile_mummy;
  d.hp = 44;
  d.spi = 60;
  d.dmgMelee = 6;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.spawnMinDLVL = FIRST_CAVERN_LEVEL - 1;
  d.isAutoSpawnAllowed = false;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.canOpenDoors = true;
  d.nrTurnsAwarePlayer = 9999;
  d.description = "The mummified fourth dynasty Egyptian pharaoh Khephren. How he came to dwell here is beyond my guess. His name means \"Rise, Ra!\"";
  d.spellCastMessage = "Khephren casts a spell.";
  d.erraticMovement = actorErratic_rare;
  d.monsterShockLevel = monsterShockLevel_terrifying;
  d.isUndead = true;
  d.isHumanoid = true;
  d.nativeRooms.push_back(roomTheme_plain);
  addData(d);
  d.reset();

  d.name_a = "Nitokris";
  d.name_the = "Nitokris";
  d.bodyType = actorBodyType_normal;
  d.id = actor_nitokris;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.spellCooldownTurns = 3;
  d.isUnique = true;
  d.nrLeftAllowedToSpawn = 1;
  d.glyph = 'P';
  d.color = clrRedLgt;
  d.tile = tile_mummy;
  d.hp = 44;
  d.spi = 60;
  d.dmgMelee = 6;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.spawnMinDLVL = 11;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.canBashDoors = true;
  d.canOpenDoors = true;
  d.nrTurnsAwarePlayer = 9999;
  d.description = "The mummified sixth dynasty Egyptian pharaoh Nitokris. How she came to dwell here is beyond my guess. Her name is found in the histories of Herodotus and writings of Manetho. According to the writings of the former, she took the throne by inviting her brothers murderers to a banquet. Then killed them by flooding the sealed room with the Nile.";
  d.spellCastMessage = "Nitokris casts a spell.";
  d.erraticMovement = actorErratic_rare;
  d.monsterShockLevel = monsterShockLevel_terrifying;
  d.isUndead = true;
  d.isHumanoid = true;
  d.nativeRooms.push_back(roomTheme_plain);
  addData(d);
  d.reset();

  d.name_a = "A Deep One";
  d.name_the = "The Deep One";
  d.bodyType = actorBodyType_normal;
  d.id = actor_deepOne;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = true;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 15;
  d.glyph = 'F';
  d.color = clrWhite;
  d.tile = tile_deepOne;
  d.hp = 8;
  d.spi = 12;
  d.dmgMelee = 3;
  d.dmgRanged = 3;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.abilityVals.setVal(ability_accuracyRanged, 40);
  d.spawnMinDLVL = 6;
  d.groupSize = monsterGroupSize_horde;
  d.actorSize = actorSize_humanoid;
  d.isHumanoid = true;
  d.canBashDoors = true;
  d.canOpenDoors = true;
  d.nrTurnsAwarePlayer = 20;
  d.description = "Deep ones are misbegotten creatures of the deep. A deep one appears as an abominable crossbreed of a human and amphibian. Its fins are merged with twisted arms and legs; its bent back is crowned with a long, spiny frill. They can breathe both air and water. In the timeless depths of the sea, the deep one's alien, arrogant lives are coldly beautiful, unbelievably cruel, and effectively immortal. Deep ones may be worshipped by humans with whom they regularly interbreed.";
  d.erraticMovement = actorErratic_rare;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.nativeRooms.push_back(roomTheme_flooded);
  d.nativeRooms.push_back(roomTheme_muddy);
  addData(d);
  d.reset();

  d.name_a = "A Mass of Worms";
  d.name_the = "The Mass of Worms";
  d.bodyType = actorBodyType_normal;
  d.id = actor_wormMass;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = false;
  d.speed = actorSpeed_slow;
  d.rangedCooldownTurns = 0;
  d.glyph = 'w';
  d.color = clrWhite;
  d.tile = tile_massOfWorms;
  d.hp = 2;
  d.spi = 1;
  d.dmgMelee = 2;
  d.abilityVals.setVal(ability_accuracyMelee, 20);
  d.spawnMinDLVL = 4;
  d.spawnMaxDLVL = d.spawnMinDLVL + 5;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 10;
  d.description = "A slithering conglomeration of carnivorous worms. They multiply rapidly.";
  d.isAutoDescriptionAllowed = false;
  d.erraticMovement = actorErratic_very;
  d.canBleed = false;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_monster);
  addData(d);
  d.reset();

  d.name_a = "A Dust Vortex";
  d.name_the = "The Dust Vortex";
  d.bodyType = actorBodyType_flying;
  d.id = actor_dustVortex;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = false;
  d.speed = actorSpeed_normal;
  d.rangedCooldownTurns = 0;
  d.glyph = 'V';
  d.color = clrGray;
  d.tile = tile_vortex;
  d.hp = 10;
  d.spi = 12;
  d.dmgMelee = 4;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.spawnMinDLVL = 8;
  d.spawnMaxDLVL = d.spawnMinDLVL + 5;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.nrTurnsAwarePlayer = 5;
  d.isAutoDescriptionAllowed = true;
  d.canOpenDoors = false;
  d.canBashDoors = true;
  d.description = "A spinning force of destruction. It seems to move with some manner of purpose.";
  d.aggroTextMonsterHidden = "I hear a howling wind.";
  d.canBleed = false;
  d.canBeSummoned = true;
  d.erraticMovement = actorErratic_very;
  d.monsterShockLevel = monsterShockLevel_unsettling;
  d.nativeRooms.push_back(roomTheme_plain);
  addData(d);
  d.reset();

  d.name_a = "A Fire Vortex";
  d.name_the = "The Fire Vortex";
  d.bodyType = actorBodyType_flying;
  d.id = actor_fireVortex;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = false;
  d.speed = actorSpeed_normal ;
  d.rangedCooldownTurns = 0;
  d.glyph = 'V';
  d.color = clrRed;
  d.tile = tile_vortex;
  d.hp = 16;
  d.spi = 12;
  d.dmgMelee = 6;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.intrProps[propRFire] = true;
  d.spawnMinDLVL = 13;
  d.groupSize = monsterGroupSize_few;
  d.actorSize = actorSize_humanoid;
  d.nrTurnsAwarePlayer = 5;
  d.isAutoDescriptionAllowed = true;
  d.canOpenDoors = false;
  d.canBashDoors = true;
  d.description = "A spinning force of fire and destruction. It seems to move with some manner of purpose.";
  d.aggroTextMonsterHidden = "I hear a howling wind.";
  d.canBleed = false;
  d.canBeSummoned = true;
  d.erraticMovement = actorErratic_very;
  d.monsterShockLevel = monsterShockLevel_unsettling;
  d.nativeRooms.push_back(roomTheme_plain);
  addData(d);
  d.reset();

  d.name_a = "A Black Ooze";
  d.name_the = "The Black Ooze";
  d.bodyType = actorBodyType_ooze;
  d.id = actor_oozeBlack;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_sluggish;
  d.rangedCooldownTurns = 0;
  d.glyph = 'o';
  d.color = clrGray;
  d.tile = tile_ooze;
  d.hp = 10;
  d.spi = 12;
  d.dmgMelee = 3;
  d.abilityVals.setVal(ability_accuracyMelee, 34);
  d.spawnMinDLVL = 3;
  d.spawnMaxDLVL = d.spawnMinDLVL + 5;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 250;
  d.isAutoDescriptionAllowed = true;
  d.canOpenDoors = false;
  d.canBashDoors = false;
  d.description = "It's just a mass of gunk, but it seems sentient.";
  d.deathMessageOverride = "The Ooze disintegrates.";
  d.aggroTextMonsterSeen = d.name_the + " makes a gurgling noise.";
  d.aggroTextMonsterHidden = "I hear a gurgling noise.";
  d.canBleed = false;
  d.canBeSummoned = true;
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_unsettling;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_flooded);
  d.nativeRooms.push_back(roomTheme_muddy);
//  d.nativeRooms.push_back(roomTheme_chasm);
  addData(d);
  d.reset();

  d.name_a = "A Clear Ooze";
  d.name_the = "The Clear Ooze";
  d.bodyType = actorBodyType_ooze;
  d.id = actor_oozeClear;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_sluggish;
  d.rangedCooldownTurns = 0;
  d.glyph = 'o';
  d.color = clrWhiteHigh;
  d.tile = tile_ooze;
  d.hp = 13;
  d.spi = 12;
  d.dmgMelee = 4;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.abilityVals.setVal(ability_stealth, 90);
  d.spawnMinDLVL = 4;
  d.spawnMaxDLVL = d.spawnMinDLVL + 5;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 250;
  d.isAutoDescriptionAllowed = true;
  d.canOpenDoors = false;
  d.canBashDoors = false;
  d.description = "It's a clear mass of gunk. They can be hard to spot.";
  d.deathMessageOverride = "The Ooze disintegrates.";
  d.aggroTextMonsterSeen = d.name_the + " makes a gurgling noise.";
  d.aggroTextMonsterHidden = "I hear a gurgling noise.";
  d.canBleed = false;
  d.canBeSummoned = true;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.erraticMovement = actorErratic_somewhat;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_flooded);
  d.nativeRooms.push_back(roomTheme_muddy);
//  d.nativeRooms.push_back(roomTheme_chasm);
  addData(d);
  d.reset();

  d.name_a = "A Putrid Ooze";
  d.name_the = "The Putrid Ooze";
  d.bodyType = actorBodyType_ooze;
  d.id = actor_oozePutrid;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_sluggish;
  d.rangedCooldownTurns = 0;
  d.glyph = 'o';
  d.color = clrGreen;
  d.tile = tile_ooze;
  d.hp = 16;
  d.spi = 12;
  d.dmgMelee = 15;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.spawnMinDLVL = 5;
  d.spawnMaxDLVL = d.spawnMinDLVL + 5;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 250;
  d.isAutoDescriptionAllowed = true;
  d.canOpenDoors = false;
  d.canBashDoors = false;
  d.description = "It's just a mass of gunk, but it seems sentient. It stinks like rotting cadavers.";
  d.deathMessageOverride = "The Ooze disintegrates.";
  d.aggroTextMonsterSeen = d.name_the + " makes a gurgling noise.";
  d.aggroTextMonsterHidden = "I hear a gurgling noise.";
  d.canBleed = false;
  d.canBeSummoned = true;
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_flooded);
  d.nativeRooms.push_back(roomTheme_muddy);
//  d.nativeRooms.push_back(roomTheme_chasm);
  addData(d);
  d.reset();

  d.name_a = "A Poison Ooze";
  d.name_the = "The Poison Ooze";
  d.bodyType = actorBodyType_ooze;
  d.id = actor_oozePoison;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_sluggish;
  d.rangedCooldownTurns = 0;
  d.glyph = 'o';
  d.color = clrGreenLgt;
  d.tile = tile_ooze;
  d.hp = 27;
  d.spi = 12;
  d.dmgMelee = 7;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.abilityVals.setVal(ability_accuracyRanged, 40);
  d.spawnMinDLVL = 9;
  d.spawnMaxDLVL = d.spawnMinDLVL + 5;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_group;
  d.actorSize = actorSize_floor;
  d.nrTurnsAwarePlayer = 250;
  d.isAutoDescriptionAllowed = true;
  d.canOpenDoors = false;
  d.canBashDoors = false;
  d.description = "It's just a mass of gunk, but it seems sentient. It drips and sizzles with poison.";
  d.deathMessageOverride = "The Ooze disintegrates.";
  d.aggroTextMonsterSeen = d.name_the + " makes a gurgling noise.";
  d.aggroTextMonsterHidden = "I hear a gurgling noise.";
  d.canBleed = false;
  d.canBeSummoned = true;
  d.erraticMovement = actorErratic_somewhat;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_flooded);
  d.nativeRooms.push_back(roomTheme_muddy);
//  d.nativeRooms.push_back(roomTheme_chasm);
  addData(d);
  d.reset();

  d.name_a = "A Colour out of space";
  d.name_the = "The Colour out of space";
  d.bodyType = actorBodyType_ooze;
  d.id = actor_colourOutOfSpace;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = true;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = false;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = true;
  d.speed = actorSpeed_sluggish;
  d.rangedCooldownTurns = 0;
  d.glyph = 'O';
  d.color = clrGreenLgt;
  d.tile = tile_ooze;
  d.hp = 64;
  d.spi = 40;
  d.dmgMelee = 10;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.spawnMinDLVL = 14;
  d.spawnMaxDLVL = 999;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.nrTurnsAwarePlayer = 250;
  d.canOpenDoors = false;
  d.canBashDoors = false;
  d.description = "A very peculiar floating speck of strange and shifting colours. It is hard to tell what colour it is exactly.";
  d.isAutoDescriptionAllowed = false;
  d.deathMessageOverride = "The Colour disintegrates.";
  d.canBleed = false;
  d.canBeSummoned = true;
  d.erraticMovement = actorErratic_very;
  d.monsterShockLevel = monsterShockLevel_scary;
  d.nativeRooms.push_back(roomTheme_plain);
  d.nativeRooms.push_back(roomTheme_flooded);
  d.nativeRooms.push_back(roomTheme_muddy);
  addData(d);
  d.reset();

  d.name_a = "A Hunting Horror";
  d.name_the = "The Hunting Horror";
  d.bodyType = actorBodyType_flying;
  d.id = actor_huntingHorror;
  d.aiBehavior.looks = true;
  d.aiBehavior.makesRoomForFriend = false;
  d.aiBehavior.triesAttack = true;
  d.aiBehavior.pathsToTargetWhenAware = true;
  d.aiBehavior.movesTowardTargetWhenVision = true;
  d.aiBehavior.movesTowardLair = false;
  d.aiBehavior.movesTowardLeader = false;
  d.speed = actorSpeed_fastest;
  d.rangedCooldownTurns = 0;
  d.glyph = 'W';
  d.color = clrGray;
  d.tile = tile_huntingHorror;
  d.hp = 58;
  d.spi = 40;
  d.dmgMelee = 10;
  d.abilityVals.setVal(ability_accuracyMelee, 40);
  d.spawnMinDLVL = LAST_CAVERN_LEVEL - 1;
  d.spawnMaxDLVL = 999;
  d.canSeeInDarkness = true;
  d.groupSize = monsterGroupSize_alone;
  d.actorSize = actorSize_humanoid;
  d.nrTurnsAwarePlayer = 2;
  d.isAutoDescriptionAllowed = true;
  d.canOpenDoors = false;
  d.canBashDoors = true;
  d.description = "It resembles an enormous black ropy worm, like a legless dragon seen in a nightmare. A great gaping maw filled with jagged, irregular teeth gapes open hungrily as it flies in search of prey. Hunting horrors haunt the dark places of the universe, from which they are called up at the whim of their lord Nyarlathotep.";
  d.canBleed = true;
  d.canBeSummoned = false;
  d.monsterShockLevel = monsterShockLevel_mindShattering;
  d.erraticMovement = actorErratic_somewhat;
//  d.nativeRooms.push_back(roomTheme_chasm);
  addData(d);
  d.reset();
}

